nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@patternfly/react-icons@*":
    dependencies:
      "tslib": "*"
  "@types/react-tooltip@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "connected-react-router@*":
    dependencies:
      "immutable": "*"
      "seamless-immutable": "*"
  "react-pluralize@*":
    dependencies:
      "prop-types": "*"

httpTimeout: 600000
httpRetry: 3
